# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# This pipeline will be extended to the OneESPT template

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: 1ES-ABTT-Shared-Pool
        image: abtt-windows-2022
        os: windows
    pool:
      name: 1ES-ABTT-Shared-Pool
      image: abtt-ubuntu-2204
      os: linux
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - template: /.pipelines/build-package.yml@self
        parameters:
          name: 'build_language_service'
          root: 'language-service'
          packagename: 'azure-pipelines-language-service'
          tarballPath: 'language-service'
          configuration: 'ci'
      - template: /.pipelines/build-package.yml@self
        parameters:
          name: 'build_language_server'
          root: 'language-server'
          packagename: 'azure-pipelines-language-server'
          tarballPath: 'language-server'
          configuration: 'ci'