# CI and PR build script for language-service and language-server

trigger:
- main

jobs:
- template: build-package.yml
  parameters:
    name: 'build_language_service'
    root: 'language-service'
    packagename: 'azure-pipelines-language-service'
    tarballPath: 'language-service'
    configuration: 'ci'

- template: build-package.yml
  parameters:
    name: 'build_language_server'
    root: 'language-server'
    packagename: 'azure-pipelines-language-server'
    tarballPath: 'language-server'
    configuration: 'ci'
