# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# This pipeline will be extended to the OneESPT template

# Release build script for language-server
# Only trigger manually
parameters:
- name: dryRun
  displayName: Build and validate without publishing
  type: boolean
  default: false

trigger: none
pr: none
variables:
- group: esrp-npm-release
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    settings:
      networkIsolationPolicy: Permissive,Npm
    sdl:
      sourceAnalysisPool:
        name: 1ES-ABTT-Shared-Pool
        image: abtt-windows-2025
        os: windows
    pool:
      name: 1ES-ABTT-Shared-Pool
      image: abtt-ubuntu-2404
      os: linux
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - template: /.pipelines/release-package.yml@self
      parameters:
        name: 'build_language_server'
        root: 'language-server'
        packagename: 'azure-pipelines-language-server'
        dryRun: ${{ parameters.dryRun }}